name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  scalafmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: coursier/setup-action@v1
        with:
          apps: scalafmt
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          files: |
            **.scala
            **.sbt
      - name: Run Scalafmt on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: scalafmt ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Check if there are any changes
        id: verify-diff
        run: git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit files
        if: steps.verify-diff.outputs.changed == 'true'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -a -m "style: Run Scalafmt"
      - name: Push changes
        if: steps.verify-diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

  test:
    runs-on: ubuntu-latest
    env:
      EMBEDDED_REDIS: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Install sbt
      uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt coverage test coverageReport
    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./target/scala-3.3.4/scoverage-report/scoverage.xml

  assembly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Install sbt
      uses: sbt/setup-sbt@v1
    - name: Run assembly
      run: sbt assembly
    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: medicate-assembly.jar
        path: target/scala-3.3.4/medicate-assembly-0.1.0.jar